# _*_ restclient _*_
:auth = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2MTBhZDhjLWM4OTEtNDYwYi05MDk0LTMzMjdiZDk0YTAyMSIsInVzZXJuYW1lIjoibnVzYXlyYSIsImlhdCI6MTU4Nzk2ODc4MiwiZXhwIjoxNTg4NTczNTgyfQ.RiH_g6UD-k4CrMC4evLaduJmAGBqSqNyKxVRnIrywxQ

:ideaId = a2ef84c0-a07a-4db8-bf71-d2f0a2b51501

# Get all ideas
GET http://localhost:4000/api/ideas


# Create an idea
POST http://localhost:4000/api/ideas
content-type: application/json
:auth

{
    "idea": "play play",
    "description": "play with zayan"
}


# Get an idea by id
GET http://localhost:4000/api/ideas/:ideaId

# get an idea
GET http://localhost:4000/api/ideas/1234142524

# Update an idea
PUT http://localhost:4000/api/ideas/:ideaId
content-type: application/json
:auth

{
    "idea": "Driving challenge",
    "description": "Drive the car through the jungle"
}

# Delete an Idea
DELETE http://localhost:4000/api/ideas/:ideaId
:auth


# Bookmark an Idea
POST http://localhost:4000/api/ideas/:ideaId/bookmark
:auth

# Unbookmark an Idea
DELETE http://localhost:4000/api/ideas/:ideaId/bookmark
:auth

# Upvote an Idea
POST http://localhost:4000/api/ideas/:ideaId/upvote
:auth

# Downvote an Idea
POST http://localhost:4000/api/ideas/:ideaId/downvote
:auth
