# -*- mode: restclinet -*-
#
:headers = <<
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4YzQ3MjlmLTEzOWItNGY0MC05MTk4LWU3YmZkZDY3ZTUyYyIsInVzZXJuYW1lIjoiemF5YW4iLCJpYXQiOjE1ODc1NDY2NzgsImV4cCI6MTU4ODE1MTQ3OH0.scnsdjv_lsDd9h2jbUmQ5sTnyUEkeqqjDr29JSFQZAU
#

# Get users
GET http://localhost:4000/api/users


# Register
POST http://localhost:4000/api/users/register
content-type: application/json
{
    "username": "nusayra",
    "password": "123456"
}

# login
POST http://localhost:4000/api/users/login
content-type: application/json

{
    "username": "zayan",
    "password": "habijabi"
}
